server:
  port: 8762

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  application:
    name: nativeconfigserver
  profiles:
    active: native